Feature/website
Lipoic/Lipoic-Site pull request #2
Opened 2022-12-14 13:43 UTC by banahaker

# Description

website original design

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas

2022-12-21 15:19 UTC, SiongSng commented
我明天來 review 我先去睡覺

2022-12-22 06:01 UTC, Luminous-Coder commented
最下面的版權宣告分兩行比較好吧？或是加個句號什麼的

2022-12-22 09:11 UTC, SiongSng commented
應該寫這樣會比較好
```
Copyright © 2022 Lipoic. All rights reserved.```

2022-12-22 09:12 UTC, SiongSng requested changes

2022-12-22 09:12 UTC, SiongSng commented on index.html
> +    <footer>Copyright © 2022 Lipoic Team All rights reserved.</footer>
應該寫這樣會比較好

```suggestion
    <footer>Copyright © 2022 Lipoic. All rights reserved.</footer>
```

2022-12-22 09:12 UTC, SiongSng commented on index.html
> +      <a href="#">Learn More</a>
應該翻譯為中文，或者是新增多國語言來顯示英文，因為我們的使用者不見得看得懂

2022-12-22 09:14 UTC, SiongSng requested changes

2022-12-22 09:14 UTC, SiongSng commented on index.html
> +          <p>課程</p>
有... 兩個課程？

2022-12-22 09:14 UTC, SiongSng commented on index.html
> +          src="https://raw.githubusercontent.com/Lipoic/Lipoic-Assets/main/logo/logo.svg"
建議不要使用外部來源的檔案，如果 Github 掛掉就看不到 logo
直接把圖片放在網站裡面就好

2022-12-22 10:44 UTC, banahaker commented on index.html
> +          src="https://raw.githubusercontent.com/Lipoic/Lipoic-Assets/main/logo/logo.svg"
你覺得 github 和我們的網站誰比較容易爆掉

2022-12-22 10:57 UTC, SiongSng commented on index.html
> +          src="https://raw.githubusercontent.com/Lipoic/Lipoic-Assets/main/logo/logo.svg"
就算是這樣，我覺得圖片不要放在外部來源
直接放在 images 那個資料夾內

2022-12-22 11:12 UTC, SiongSng commented on index.html
> +      <a href="#">Learn More</a>
![image](https://user-images.githubusercontent.com/48402225/209122069-0c42a510-09e7-4f45-8498-03f63c5f46d2.png)

@banahaker 你好像還沒改，但上面顯示你已經選擇已解決

2022-12-23 03:05 UTC, Luminous-Coder commented on index.html
> +          src="https://raw.githubusercontent.com/Lipoic/Lipoic-Assets/main/logo/logo.svg"
+1

2022-12-23 13:39 UTC, SiongSng requested changes
RWD 壞了要處理#
![image](https://user-images.githubusercontent.com/48402225/209345163-a2b02d5b-e0e0-41b6-b4bf-32c1d62f4d5e.png)

2022-12-23 14:53 UTC, SiongSng approved these changes
LGTM

2022-12-23 14:54 UTC, merged