feat: contact us block
Lipoic/Lipoic-Site pull request #4
Opened 2022-12-24 09:06 UTC by banahaker

# Description

Contact us block. Contain email and discord server link.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas

2022-12-24 09:10 UTC, SiongSng requested changes

2022-12-24 09:10 UTC, SiongSng commented on index.html
> +            >https://discord.gg/ArKk54ajfr</a
Discord 連結的顏色不夠清楚，難以閱讀
![image](https://user-images.githubusercontent.com/48402225/209428981-d160f4c9-a2c0-438e-a443-e1a2e96f32a7.png)

2022-12-25 06:32 UTC, SiongSng requested changes

2022-12-25 06:32 UTC, SiongSng commented on index.html
> +          <p>lipoic.service@gmail.com</p>
```suggestion
          <p>contact@lipoic.org</p>
```
這個 email 才對

2022-12-25 06:32 UTC, SiongSng commented on index.html
> +            ><i class="bx bxl-discord-alt"></i
![image](https://user-images.githubusercontent.com/48402225/209459022-403d7615-3ff6-4d46-a052-6d04a918cb38.png)
圖示的位置怪怪的 沒置中

2022-12-27 02:41 UTC, Luminous-Coder reviewed
這裡的括號為什麼長這樣

2022-12-27 02:41 UTC, Luminous-Coder commented on index.html
> +          ></a>
101-103

2022-12-27 02:41 UTC, Luminous-Coder commented on index.html
> +          ></a>
106-108

2023-01-02 14:09 UTC, Luminous-Coder commented on index.html
> +        </div>
Use `mailto`.

2023-01-20 12:40 UTC, Luminous-Coder commented
A commit should do only one thing.

2023-01-21 14:14 UTC, banahaker commented
sorry i forgot that, i'll do it better

2023-01-22 02:17 UTC, SiongSng requested changes
大部分都不錯，只差這個

2023-01-22 02:17 UTC, SiongSng commented on index.html
> +          <i class="bx bx-envelope"></i>
在手機的畫面上建議調整佈局
像是把 Email 改成單獨一行
Discord 與 Github 改到另外一行
![image](https://user-images.githubusercontent.com/48402225/213897611-93d3508a-0021-4a71-850a-ef287ad873f0.png)

2023-01-22 15:28 UTC, Luminous-Coder requested changes

2023-01-22 15:28 UTC, Luminous-Coder commented on index.html
> +          >
這樣的話不是只有字可以點嗎？應該要整個藍色區域都可以吧？

2023-02-03 13:02 UTC, SiongSng commented on index.html
> +          >
我改好惹

2023-02-03 14:17 UTC, SiongSng approved these changes
LGTM

2023-02-04 01:10 UTC, Luminous-Coder requested changes

2023-02-04 01:10 UTC, Luminous-Coder commented on index.html
> +          <p style="color: white">contact@lipoic.org</p>
這邊直接寫 `style` 不好吧？

2023-02-04 03:32 UTC, SiongSng commented on index.html
> +          <p style="color: white">contact@lipoic.org</p>
確實，我改好惹

2023-02-04 04:22 UTC, Luminous-Coder approved these changes

2023-02-04 04:23 UTC, merged